# Generated by Django 3.0.1 on 2020-04-27 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentpay_monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_year', models.CharField(blank=True, max_length=120, null=True)),
                ('pay_month', models.CharField(blank=True, max_length=120, null=True)),
                ('pay_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Studentpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_appnum_teach', models.CharField(blank=True, max_length=120, null=True)),
                ('pay_appnum_txt', models.CharField(blank=True, max_length=120, null=True)),
                ('pay_txtbook', models.CharField(blank=True, max_length=120, null=True)),
                ('pay_txtpay', models.IntegerField(blank=True, default=0, null=True)),
                ('pay_teachpay', models.IntegerField(blank=True, default=0, null=True)),
                ('pay_memo', models.TextField(blank=True, null=True)),
                ('pay_monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Studentpay_monthly')),
                ('pay_stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Studentinfo')),
            ],
        ),
    ]
