# Generated by Django 3.0.1 on 2020-04-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_name', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_num', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_category', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_card', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_cardbank', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_validdate', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_subj', models.CharField(blank=True, max_length=120, null=True)),
                ('stu_money', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['stu_name'],
            },
        ),
    ]
